name: Build and Release Android APK

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '8'

    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.4.1'

    - name: Flutter Pub Get
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --release

    - name: Upload APK to Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: build/app/outputs/flutter-apk/app-release.apk
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: 'v1.0.${{ github.run_number }}'
        name: Release v1.0.${{ github.run_number }}
        body: |
          Automatic build and release of the Android APK.
        draft: false
        prerelease: false
